[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = false

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.http_service]
    internal_port = 8080
    force_https = false

[http_service]
    force_https = false
